# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parse a character vector of URLs into component parts
#'
#' @md
#' @param urls character vector of URLs
#' @return data frame (tibble)
#' @export
parse_curl <- function(urls) {
    .Call('_curlparse_parse_curl', PACKAGE = 'curlparse', urls)
}

#' Parse a character vector of URLs into component parts (`urltools` compatibility function)
#'
#' @md
#' @param urls character vector of URLs
#' @return data frame (not a tibble)
#' @export
url_parse <- function(urls) {
    .Call('_curlparse_url_parse', PACKAGE = 'curlparse', urls)
}

#' Extract member components from a URL string
#'
#' @md
#' @param urls character vector of URLs
#' @return character vector of the extracted URL component
#' @export
scheme <- function(urls) {
    .Call('_curlparse_scheme', PACKAGE = 'curlparse', urls)
}

#' @rdname scheme
#' @export
user <- function(urls) {
    .Call('_curlparse_user', PACKAGE = 'curlparse', urls)
}

#' @rdname scheme
#' @export
password <- function(urls) {
    .Call('_curlparse_password', PACKAGE = 'curlparse', urls)
}

#' @rdname scheme
#' @export
host <- function(urls) {
    .Call('_curlparse_host', PACKAGE = 'curlparse', urls)
}

#' @rdname scheme
#' @export
port <- function(urls) {
    .Call('_curlparse_port', PACKAGE = 'curlparse', urls)
}

#' @rdname scheme
#' @export
path <- function(urls) {
    .Call('_curlparse_path', PACKAGE = 'curlparse', urls)
}

#' @rdname scheme
#' @export
url_options <- function(urls) {
    .Call('_curlparse_url_options', PACKAGE = 'curlparse', urls)
}

#' @rdname scheme
#' @export
query <- function(urls) {
    .Call('_curlparse_query', PACKAGE = 'curlparse', urls)
}

#' @rdname scheme
#' @export
fragment <- function(urls) {
    .Call('_curlparse_fragment', PACKAGE = 'curlparse', urls)
}

